name: Test-Python

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - '**'

jobs:
  test-python:
    name: Test My Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
